### ISSUE TITLE
Handle spaces in src path correctly

### ISSUE THREAD

**Issue by NickNo-dev** [Rizean/lp-builder#14]
Using the builder on windows it will fail if there are spaces in the src path!
The target path is ok with spaces.

lpBuilder-win-x64.exe build "D:\path with spaces" "D:\another path with spaces"

`notice: Building source: D:\another path with spaces  destination: D:\path with spaces
error: Cannot read property 'children' of null
TypeError: Cannot read property 'children' of null
    at buildPhaseOne (D:\snapshot\lp-builder\src\processors\buildPhaseOne.js)
    at build (D:\snapshot\lp-builder\src\build.js)
    at Object.handler (D:\snapshot\lp-builder\src\index.js)
    at Object.runCommand (D:\snapshot\lp-builder\node_modules\yargs\build\index.cjs:446:48)
    at Object.parseArgs [as _parseArgs] (D:\snapshot\lp-builder\node_modules\yargs\build\index.cjs:2697:57)
    at Object.get [as argv] (D:\snapshot\lp-builder\node_modules\yargs\build\index.cjs:2651:25)
    at Object.<anonymous> (D:\snapshot\lp-builder\src\index.js)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
error: Cannot read property 'children' of null
TypeError: Cannot read property 'children' of null
    at buildPhaseTwo (D:\snapshot\lp-builder\src\processors\buildPhaseTwo.js)
    at build (D:\snapshot\lp-builder\src\build.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1376:13)
    at internal/main/run_main_module.js:17:47
error: Cannot read property 'children' of null
TypeError: Cannot read property 'children' of null
    at buildPhaseFour (D:\snapshot\lp-builder\src\processors\buildPhaseFour.js)
    at build (D:\snapshot\lp-builder\src\build.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1376:13)
    at internal/main/run_main_module.js:17:47
error: Cannot read property 'children' of null
TypeError: Cannot read property 'children' of null
    at buildPhaseFinal (D:\snapshot\lp-builder\src\processors\buildPhaseFinal.js)
    at build (D:\snapshot\lp-builder\src\build.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1376:13)
    at internal/main/run_main_module.js:17:47
`

**Comment by Rizean** [comment]
Thinking this is from the 0.0.1 ver. Not seeing this issue in 0.1.0 alpha
